PatchContratos:
  name: ${self:provider.stage}-${self:service}-PatchContratos
  handler: src/functions/PatchContratos/handler.handle
  package:
    patterns:
      - 'src/functions/PatchContratos/handler.js'
      - 'src/util/**'
      - 'src/errors/**'
  events:
    - http:
        path: ${self:custom.projectPath}/contratos
        method: patch
        integration: lambda
        authorizer:
          name: ${self:provider.stage}-${self:service}-Authorizer
          type: COGNITO_USER_POOLS
          arn:
            Fn::GetAtt:
              - CognitoUserPool
              - Arn
        response: ${file(config/schemas/responseTemplate/default200.yml)}
  iamRoleStatements:
    - Effect: "Allow"        
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
      Resource: 
        - ${cf:adv-beholder-db-${opt:env}.ContratosTableArn}