PostContratos:
  name: ${self:provider.stage}-${self:service}-PostContratos
  handler: src/functions/PostContratos/handler.handle
  package:
    patterns:
      - 'src/functions/PostContratos/handler.js'
      - 'src/util/**'
      - 'node_modules/uuid-by-string/**'
      - 'node_modules/js-md5/**'
      - 'node_modules/js-sha1/**'
  events:
    - http:
        path: ${self:custom.projectPath}/contratos
        method: post
        integration: lambda
        authorizer:
          name: ${self:provider.stage}-${self:service}-Authorizer
          type: COGNITO_USER_POOLS
          arn:
            Fn::GetAtt:
              - CognitoUserPool
              - Arn
        response: ${file(config/schemas/responseTemplate/default201.yml)}