service: adv-beholder
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  versionFunctions: false
  region: ${opt:region, 'us-east-2'}
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  stackTags:
    level0: serverless
    level1: backend
    level2: adv-beholder
  logRetentionInDays: ${env:LOG_RETENTION}

custom:
  projectPath: "adv-beholder"

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-resource-tagging
  - serverless-mocha-plugin


package:
  individually: true
  patterns:
    - '!response/**'
    - '!node_modules/**'
    - '!bitbucket-pipelines.yml'
    - '!package-lock.json'
    - '!README.md'
    - '!package.json'
    - '!config/**'
    - '!src/**'
    - '!swagger/**'
    - '!docs/**'

functions:
  - ${file(src/functions/Signup/config.yml)}
  - ${file(src/functions/Login/config.yml)}
  - ${file(src/functions/DeleteContratos/config.yml)}
  - ${file(src/functions/GetContratos/config.yml)}
  - ${file(src/functions/PatchContratos/config.yml)}
  - ${file(src/functions/PostContratos/config.yml)}
  - ${file(swagger/docs.yml)}

resources:
  - ${file(config/resources/cognito.yml)}
  - ${file(config/resources/outputs.yml)}

