GetTeste:
  name: ${self:provider.stage}-${self:service}-GetTeste
  handler: src/functions/GetTeste/handler.handle
  package:
    patterns:
      - 'src/functions/GetTeste/handler.js'
  events:
    - http:
        path: ${self:custom.projectPath}/teste
        method: get
        integration: lambda
        response: ${file(config/schemas/responseTemplate/default200.yml)}