DeleteContratos:
  name: ${self:provider.stage}-${self:service}-DeleteContratos
  handler: src/functions/DeleteContratos/handler.handle
  package:
    patterns:
      - 'src/functions/DeleteContratos/handler.js'
      - 'src/util/**'
  events:
    - http:
        path: ${self:custom.projectPath}/contratos/{idContrato}
        method: delete
        integration: lambda
        authorizer:
          name: ${self:provider.stage}-${self:service}-Authorizer
          type: COGNITO_USER_POOLS
          arn:
            Fn::GetAtt:
              - CognitoUserPool
              - Arn
        response: ${file(config/schemas/responseTemplate/default200.yml)}